/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
  extends?: string;
  jobs?: Jobs;
  orgCreate?: OrgCreateConfig;
  replacements?: Replacements;
  /**
   * Define which files and/or metadata types to sort on 'pony:source:sort' command.
   */
  sourceSort?: ("all" | "source" | "none") | [string];
  sourceValidate?: SourceValidate;
}
export interface Jobs {
  [k: string]: {
    steps?: (
      | {
          echo: string;
        }
      | {
          env: string;
        }
      | {
          job: string;
        }
      | {
          run: string;
        }
      | {
          sfdx: string;
        }
    )[];
  };
}
export interface OrgCreateConfig {
  generateUsername?: boolean;
}
export interface Replacements {
  [k: string]: {
    innerText?: {
      files: string[];
      replacement: string;
      search: string[];
    };
    orgWideEmailAddress?: {
      files: string[];
      replacement: string;
    };
  };
}
export interface SourceValidate {
  deleteOrg?: boolean | ("always" | "never" | "onSuccess");
  trackedFieldHistory?: boolean | ["error" | "warning" | "info", number, ...string[]];
}
