/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SObjectName = string;
export type RelationshipField = string;

export interface DataConfig {
  sObjects?: {
    recordsDir?: string;
    import?: {
      chunkSize?: number;
      deleteBeforeImport?: (false | "reversedOrder") | SObjectName[];
      soqlDeleteDir?: string;
      order: SObjectName[];
      relationships?: {
        [k: string]: RelationshipField[];
      };
    };
    export?: {
      soqlExportDir?: string;
      order?: SObjectName[] | "reversedOrder";
    };
  };
}
