/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SObjects = string[];

export interface DataConfig {
  import?: {
    deleteBeforeImport?: (true | false | "reversed") | SObjects;
    sObjects: SObjects;
    relationships?: Relationship[];
  };
  export?: {
    sObjects: SObjects;
  };
}
export interface Relationship {
  sObject: string;
  fieldMappings: FieldMapping[];
}
export interface FieldMapping {
  source: string;
  target: string;
}
