/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrgCreateConfig {
  generateUsername?: boolean;
  /**
   * do not include second-generation package ancestors in the scratch org
   */
  noAncestors?: boolean;
  /**
   * create the scratch org with no namespace
   */
  noNamespace?: boolean;
  /**
   * duration of the scratch org (in days)
   */
  durationDays?: number;
  /**
   * path to an org definition file
   */
  definitionFile?: string;
}
